"""Economic configuration for the ESP maintenance simulation.

``PumpModel`` only knows about physical degradation and sensor behaviour --
it never computes a dollar figure. Anything that turns a physical outcome
(flow produced, an hour of downtime, a failure) into money belongs here
instead, so the numbers can be reported on, swapped, or retuned for a
different reward structure without touching the simulator.

The RL environment (a later phase) will combine these into a per-step
reward. This module intentionally stops at configuration plus small pure
pricing helpers -- it does not decide *when* costs are incurred, only
*how much* they cost once they are.

All figures below are simulation assumptions used to build and exercise
the RL pipeline. They are illustrative and are not sourced from real
SOCAR or industry cost data.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EconomicsConfig:
    revenue_per_flow_unit: float = 2.0
    energy_cost_per_power_unit: float = 0.25
    inspection_cost: float = 150.0
    preventive_maintenance_cost: float = 900.0
    corrective_maintenance_cost: float = 2500.0
    downtime_cost_per_hour: float = 100.0
    failure_penalty: float = 5000.0


def production_revenue(flow_rate: float, config: EconomicsConfig) -> float:
    """Revenue generated by one hour of production at the given flow rate."""

    return flow_rate * config.revenue_per_flow_unit


def energy_cost(power_consumption: float, config: EconomicsConfig) -> float:
    """Cost of the energy drawn during one operating hour."""

    return power_consumption * config.energy_cost_per_power_unit


def downtime_cost(downtime_hours: float, config: EconomicsConfig) -> float:
    """Cost of downtime accrued while the pump is offline for maintenance."""

    return downtime_hours * config.downtime_cost_per_hour
